# This is a basic workflow to help you get started with Actions

name: CI

# Trigger the workflow on push or pull request
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    # Runs a set of commands using the runners shell
    - name: msbuild
      run: msbuild Microsoft.Exchange.WebServices.Data.sln -p:Configuration=Release
      
    - name: Download artifact
      uses: actions/upload-artifact@v1
      with:
        # Artifact name
        name: Compiled
        # Destination path
        path: bin/Release
    
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/KULL-ag/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./bin/Release/*.nupkg --skip-duplicate --no-symbols true


